<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Multi-target: net472 para la Raspberry Pi, net10.0 para desarrollo local en Mac/PC -->
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <!-- Optimizado para Raspberry Pi Zero W (ARMv6) -->
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\NubeZero.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>

</Project>
