<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Usando .NET Framework 4.7.2 para compatibilidad total con Mono en Linux -->
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Optimizado para Raspberry Pi Zero W (ARMv6) -->
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\NubeZero.Shared.csproj" />
  </ItemGroup>

</Project>
